name: Build Node-RED

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Dockerfile

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: vimagick/dockerfiles/.github/actions/docker-build-notify@master
        with:
          image_name: 'easypi/node-red'
          version_arg: 'NODERED_VERSION'
          version_value: '5.0.5'
          other_build_args: |
            NODERED_DASHBOARD_VERSION=1.31.0
