name: Docker Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  NODERED_VERSION: '2.1.6'
  NODERED_ADMIN_VERSION: '2.2.1'
  NODERED_DASHBOARD_VERSION: '3.1.5'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            NODERED_VERSION=${{ env.NODERED_VERSION }}
            NODERED_ADMIN_VERSION=${{ env.NODERED_ADMIN_VERSION }}
            NODERED_DASHBOARD_VERSION=${{ env.NODERED_DASHBOARD_VERSION }}
          tags: |
            easypi/node-red:latest
            easypi/node-red:${{ env.NODERED_VERSION }}
          push: true

      - if: ${{ always() }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: github
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "text": "docker build image result",
                  "fields": [
                    {
                      "title": "Image",
                      "value": "easypi/node-red",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ],
                  "footer": "Github Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
